[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/search/*"
  to = "https://plaything-cornbread-exhale.pgsdemo.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://plaything-cornbread-exhale.pgsdemo.com"}

[[redirects]]
  from = "/search"
  to = "https://plaything-cornbread-exhale.pgsdemo.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://plaything-cornbread-exhale.pgsdemo.com/"}
