[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/search/*"
  to = "https://master-wildly--various--lacewing-sbx-pgsdemo-com.sbx.preview.pagescdn.com/:splat"
  status = 200
  force = true
  headers = {Host = "https://master-wildly--various--lacewing-sbx-pgsdemo-com.sbx.preview.pagescdn.com"}

[[redirects]]
  from = "/search"
  to = "https://master-wildly--various--lacewing-sbx-pgsdemo-com.sbx.preview.pagescdn.com/index.html"
  status = 200
  force = true
  headers = {Host = "https://master-wildly--various--lacewing-sbx-pgsdemo-com.sbx.preview.pagescdn.com/"}
